language: android

notifications:
  email: false

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-20.0.0
    - android-20

install: true

script: ./gradlew connectedAndroidTest
