language: android
notifications:
  email: false
install: true
env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-20.0.0

script: ./gradlew connectedAndroidTest
