language: android

notifications:
  email: false

env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-22.0.1
    - android-21

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

install: true

script: ./gradlew connectedAndroidTest
