language: android

notifications:
  email: false

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-20.0.0

before_install:
  - echo "sdk.dir=$ANDROID_HOME" > local.properties

install: true

script: ./gradlew connectedAndroidTest
